embed_subentry:
  name: Embed Subentry
  target:
    entity:
      domain: conversation
      integration: ha_ragent

preload_models:
  name: Preload Agent
  target:
    entity:
      domain: conversation
      integration: ha_ragent

unload_models:
  name: Unload Agent
  target:
    entity:
      domain: conversation
      integration: ha_ragent
